### ISSUE TITLE
Improve route name matching with regex

### ISSUE THREAD

**Issue by halivert** [halivert/laravel-js-routes#2]
I want to use regex to include or exclude named routes in the configuration file.

**Comment by pishguy** [comment]
+1

how can we exclude some routes in this current version

**Comment by halivert** [comment]
@MahdiPishguy with this key => value in config/app.php
```php
'jsroutes' => [
  'exclude' => [
    // Exclude routes with this names e.g.
    'telescope',
  ]
]
```

**Comment by pishguy** [comment]
@halivert 

thanks so much, worked fine, i have another question, this package can be support `*`? for example:

using 
```
'debugbar.*',
```
instead of:
```
'debugbar.openhandler',
'debugbar.clockwork',
'debugbar.telescope',
'debugbar.assets.css',
'debugbar.assets.js',
'debugbar.cache.delete',
```

**Comment by halivert** [comment]
@MahdiPishguy that's a great idea 😄 also is the topic in this issue, but I haven't started working on it yet.

**Comment by dansleboby** [comment]
Implemented in pull request #13 :)

**Comment by pishguy** [comment]
@halivert

i can't use `*` wildcard `config/app.php`

```js
'jsroutes' => [
    'exclude' => [
        'telescope.*',
        'telescope*',
        'telescope*.*',
    ]
]
```

BTW , why i can't exclude this routes?

```js
'jsroutes' => [
    'exclude' => [
        'debugbar.openhandler',
        'debugbar.clockwork',
        'debugbar.telescope',
        'debugbar.assets.css',
        'debugbar.assets.js',
        'debugbar.cache.delete',
        'dusk',
        'livewire',
        'graphql',
    ]
]
```

i recreate routes with `route:tojs` command with `yes` answer in terminal question

**Comment by halivert** [comment]
Hi @MahdiPishguy, have you updated the package to the latest version?
